config/routes.rb
RailsStrips::Application.routes.draw do
  resources :subscriptions

  resources :subscription_plans

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :subscription_plan
  attr_accessible :email, :subscription_plan_id, :stripe_card_token
  
  attr_accessor :stripe_card_token
  
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: subscription_plan_id, card: stripe_card_token)
      save!
    end
		rescue Stripe::InvalidRequestError => e
		  logger.error "Stripe error while creating customer: #{e.message}"
		  errors.add :base, "There was a problem with your credit card."
		  false
		end
end

app/models/subscription_plan.rb
class SubscriptionPlan < ActiveRecord::Base
	has_many :subscriptions
  attr_accessible :amount, :description, :id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/subscription_plans_controller.rb
class SubscriptionPlansController < ApplicationController
  # GET /subscription_plans
  # GET /subscription_plans.json
  def index
    @subscription_plans = SubscriptionPlan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscription_plans }
    end
  end
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscriptions }
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new
    plan = SubscriptionPlan.find(params[:subscription_plan_id]) 
    @subscription = plan.subscriptions.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscription }
    end
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(params[:subscription])
    if @subscription.save_with_payment
      redirect_to @subscription, :notice => "Thank you for subscribing!"
    else
      render :new
    end
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscription_plans_helper.rb
module SubscriptionPlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsStrips</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => 'stripe-key', :content => PUBLISHABLE_KEY %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/subscription_plans/index.html.erb
<h1>Listing subscription_plans</h1>


<% @subscription_plans.each do |subscription_plan| %>
  	<%= subscription_plan.id %>
    <%= subscription_plan.amount %>
    <%= subscription_plan.description %>
    <%= link_to 'Subscribe', "/subscriptions/new?subscription_plan_id=#{subscription_plan.id}" %>
  	<br />
<% end %>

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>
      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<%= f.hidden_field :subscription_plan_id %>
	
	<%= f.hidden_field :stripe_card_token %>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= label_tag :card_number, "Credit Card Number" %>
		<%= text_field_tag :card_number, nil, name: nil %>
	</div>
	<div class="field">
		<%= label_tag :card_code, "Security Code on Card (CVV)" %>
		<%= text_field_tag :card_code, nil, name: nil %>
	</div>
	<div class="field">
		<%= label_tag :card_month, "Card Expiration" %>
		<%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
		<%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
	</div>
	<div id="stripe_error">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <tr>
    <th>Plan</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= subscription.subscription_plan_id %></td>
    <td><%= subscription.email %></td>
   
  </tr>
<% end %>
</table>

<br />

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Plan:</b>
  <%= @subscription.subscription_plan_id %>
</p>

<p>
  <b>Email:</b>
  <%= @subscription.email %>
</p>